-- tree-sitter によるシンタックスハイライトを行わないファイルタイプ
local disable_highlights = {
  ['sql'] = true,
  ['php'] = true,
}
local langs = {
  'bash',
  'blade',
  'c',
  'c_sharp',
  'clojure',
  'cmake',
  'comment',
  'commonlisp',
  'cpp',
  'css',
  'csv',
  'dart',
  'diff',
  'dockerfile',
  'dot',
  'doxygen',
  'editorconfig',
  'elixir',
  'elm',
  'erlang',
  'git_config',
  'git_rebase',
  'gitattributes',
  'gitcommit',
  'gitignore',
  'go',
  'gomod',
  'gosum',
  'gotmpl',
  'gpg',
  'graphql',
  'groovy',
  'haskell',
  'hcl',
  'helm',
  'html',
  'http',
  'ini',
  'java',
  'javadoc',
  'javascript',
  'jinja',
  'jinja_inline',
  'jq',
  'jsdoc',
  'json',
  'json5',
  'jsonc',
  'julia',
  'kotlin',
  'llvm',
  'lua',
  'luadoc',
  'luap',
  'luau',
  'make',
  'markdown',
  'markdown_inline',
  'mermaid',
  'nginx',
  'nim',
  'objc',
  'perl',
  'php',
  'phpdoc',
  'po',
  'pod',
  'python',
  'query',
  'regex',
  'ruby',
  'rust',
  'scala',
  'scss',
  'slim',
  'sql',
  'ssh_config',
  'svelte',
  'terraform',
  'tmux',
  'toml',
  'tsv',
  'tsx',
  'twig',
  'typescript',
  'typespec',
  'vim',
  'vimdoc',
  'vue',
  'xml',
  'yaml',
  'zig',
}

require('nvim-treesitter').setup({ ensure_installed = langs })

local group = vim.api.nvim_create_augroup('MyTreesitterSetup', { clear = true })
vim.api.nvim_create_autocmd('FileType', {
  group = group,
  pattern = langs,
  callback = function(args)
    if disable_highlights[vim.bo[args.buf].filetype] then
      return
    end
    local ok = pcall(vim.treesitter.start, args.buf)
    if ok then
      vim.bo[args.buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
    end
  end,
})
