#!/bin/bash
set -eu

#
# http://qiita.com/koki_cheese/items/63ce83b590e3a50fc9b1
#
# branchname#123
# branchname-123
# branchname_123
# issue123
# issues123
# issue/123
# issues/123
# branchname/issue/123
# branchname/issues/123
# 123_branchname
# 123-branchname
# #123branchname

# if match , it return number only. if no match, it return branch name.
parse() {
    target=$(cat -)
    res=$(echo $target | sed -E -e "s/.*((#|issue[s]?[\/-_]?|_|-)([0-9]*)).*/\3/g")
    if [ -n "$res" ]; then
        echo $res
        return 0
    fi

    res=$(echo $target | sed -E -e "s/^([0-9]*).*/\1/g")
    if [ -n "$res" ]; then
        echo $res
        return 0
    fi

    res=$(echo $target | sed -E -e "s/^(#|issue[s]?[\/-_]?)([0-9]*)*/\2/g")
    if [ -n "$res" ]; then
        echo $res
        return 0
    fi


    echo $target
    return 1
}

branch=$(git branch | grep "*" | awk '{print $2}')
issue=$(echo $branch | parse)

if [ $branch == $issue ]; then
    exit 0
fi

if [ -z "${2+x}" ] || [ "$2" != 'message' ]; then
  echo "refs #$issue$(cat $1)" > $1
  # echo -e "refs #$issue\n$(cat $1)" > $1
fi

